<a href="https://colab.research.google.com/github/Leviatt/Red-neuronal-IoT-Firebase/blob/main/Red_neuronal_Proyecto_final_redes_de_computadores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importamos las librerias que usaremos:

In [ ]:
import json
import numpy as np
import tensorflow as tf
import pyrebase
import datetime
import threading
from time import sleep
from google.cloud import firestore

Creamos la classe *myCallback* para parar las iteraciónes de entrenamiento si llegamos a la exactitud requerida, en este caso 95%.

In [ ]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.95):
      print("\nReached 95% accuracy so cancelling training!")
      self.model.stop_training = True

Cargamos la información del servidor en firebase para poder acceder, teniendo en cuenta que *"key.json"* es el archivo key descargado de firebase y precargado en el local path 

In [ ]:
config = {
    "apiKey": "AIzaSyDrXZwGHvlfIygauIJEvSImxule6YlBU9w",
    "authDomain": "redes-c4b7d.firebaseapp.com",
    "databaseURL": "https://redes-c4b7d-default-rtdb.firebaseio.com",
    "projectId": "redes-c4b7d",
    "storageBucket": "redes-c4b7d.appspot.com",
     "serviceAccount": "key.json"
}

Ingresamos con las credenciales a firebase y descargamos la data.

In [ ]:
firebase_storage = pyrebase.initialize_app(config)
storage = firebase_storage.storage()
storage.child("data.json").download("data.json")

Arreglamos la data para entrenar el modelo:

In [ ]:
print(tf.__version__)
with open('data.json') as file:
 data = json.load(file)

callbacks = myCallback()
train_set= np.array(data["data"][0:24000])
train_label = np.array(data["label"][0:24000])
test_set=  np.array(data["data"][24000:29999])
test_label =  np.array(data["label"][24000:29999])

2.5.0


Entrenamos el modelo definiendo el número de neuronas de la capa oculta y la de salida:

In [ ]:

model = tf.keras.models.Sequential( [tf.keras.layers.Dense(128, activation=tf.nn.relu), 
                                    tf.keras.layers.Dense(3, activation=tf.nn.softmax)])
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(train_set, train_label, epochs=25,callbacks=[callbacks])

Epoch 1/25
750/750 [==============================] - 2s 2ms/step - loss: 0.7069 - accuracy: 0.6230
Epoch 2/25
750/750 [==============================] - 1s 1ms/step - loss: 0.5721 - accuracy: 0.6902
Epoch 3/25
750/750 [==============================] - 1s 1ms/step - loss: 0.5174 - accuracy: 0.7346
Epoch 4/25
750/750 [==============================] - 1s 1ms/step - loss: 0.4806 - accuracy: 0.7601
Epoch 5/25
750/750 [==============================] - 1s 1ms/step - loss: 0.4517 - accuracy: 0.7862
Epoch 6/25
750/750 [==============================] - 1s 1ms/step - loss: 0.4256 - accuracy: 0.8072
Epoch 7/25
750/750 [==============================] - 1s 1ms/step - loss: 0.4030 - accuracy: 0.8225
Epoch 8/25
750/750 [==============================] - 1s 1ms/step - loss: 0.3838 - accuracy: 0.8320
Epoch 9/25
750/750 [==============================] - 1s 1ms/step - loss: 0.3625 - accuracy: 0.8419
Epoch 10/25
750/750 [==============================] - 1s 1ms/step - loss: 0.3430 - accuracy: 0.8440

 Testeamos el modelo entrenado:

In [ ]:
model.evaluate(test_set, test_label)

188/188 [==============================] - 0s 1ms/step - loss: 0.1731 - accuracy: 0.9388


[0.1730584055185318, 0.9388231635093689]

Hacemos una rapida comparación de prediccion con valores reales tomados del test set:

In [ ]:

sal=model.predict(test_set[324:344])
s=[]
for i in(sal):
  if (i[0]>i[1]>=i[2]):
    s.append(0)
  elif (i[1]>i[2]):
    s.append(1)
  else:
    s.append(2)

print("Predicción\n")
print(np.array(s))
print("\n Label correcto\n ")
print(test_label[324:344])
error= s-test_label[324:344]
print("\n Diferencia\n")
print(np.array(error))

Predicción

[1 1 2 2 1 2 2 2 1 2 1 2 1 1 2 2 1 2 1 1]

 Label correcto
 
[1 1 2 1 1 2 2 2 1 2 1 2 1 1 2 2 1 2 1 1]

 Diferencia

[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


De la misma forma podemos hacerlo para una posición particular

In [ ]:
pos=338
i=model.predict(np.reshape(test_set[pos],(1,6)))[0]
print("predicción cruda\n")
print(i)
print("\n predicción\n")
if (i[0]>i[1]>=i[2]):
  i=0
elif (i[1]>i[2]):
  i=1
else:
  i=2

print(i)
print("\n valor real\n")
print(test_label[pos])

predicción cruda

[7.693771e-15 3.108505e-04 9.996892e-01]

 predicción

2

 valor real

2


Guardamos el modelo en el local path:

In [ ]:
model.save('model.h5')

Ahora lo guardamos como  tflite:

In [ ]:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(tflite_model)

INFO:tensorflow:Assets written to: /tmp/tmpkvtdsd90/assets


Finalmente cargamos la data de la Realtime Database y comentado dejamos el codigo para subir la data que se requiera en ausencia dle hardware:

In [ ]:
db = firebase_storage.database()
#Put info
# persona = {"SPO2": 87, "HR": 75, "sexo":1 ,"atleta": 1, "edad": 22,"temp": 37.2}
# db.child("user").child("persona").set(persona)
persona = db.child("user").child("persona").get()
edad_i=persona.val()["edad"]
genero_i=persona.val()["sexo"]
maxbpm = (220-edad_i) if (genero_i==0) else (230-edad_i)
data = [persona.val()["edad"]/80,persona.val()["sexo"],persona.val()["SPO2"]/100,
        persona.val()["atleta"],persona.val()["HR"]/maxbpm,persona.val()["temp"]/40]
data= np.array(data).reshape(1,6)
print("data descargada\n")
print(data)
i=model.predict(data)[0]
print("\n prediccion cruda del modelo \n")
print(i)
if (i[0]>i[1]>=i[2]):
  i=0
elif (i[1]>i[2]):
  i=1
else:
  i=2
print("\n etiqueta final\n")
print(i)


data descargada

[[0.275      1.         0.81       1.         0.38461538 0.93      ]]

 prediccion cruda del modelo 

[1.3603331e-10 5.4497653e-01 4.5502350e-01]

 etiqueta final

1
